name: Earthly/Maven CI

env:
  OWASP_NVD_API_KEY: ${{ secrets.OWASP_NVD_API_KEY }}
  # Workaround for: https://github.com/earthly/earthly/issues/4220
  EARTHLY_DISABLE_REMOTE_REGISTRY_PROXY: true

on:
  push:
    paths-ignore:
      - '**.md'
      - 'images/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'images/**'
  workflow_dispatch:

jobs:
  build:
    name: Builds and tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      # Maven handles caching as dependency changes
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: m2-${{ runner.os }}-

      # Earthly handles caching as a Docker layer
      - name: Use Earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ^0.8.0

      - name: Build and test
        run: ./build-as-ci +build

      - name: Execute run script
        run: ./build-as-ci +run

      # Save artifacts for build
      - name: Save Jar for main
        uses: actions/upload-artifact@v4
        with:
          name: jar-main
          if-no-files-found: error
          path: target/kunits-0-SNAPSHOT.jar

      # Support for coverage badge report. See "Generate coverage badge" step.
      - name: Save coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          if-no-files-found: error
          path: target/site/jacoco/

      # Generate coverage badge shown in the README
      # Gradle builds are similar but will require configuration the path for the
      # CSV JaCoCo report.
      - name: Generate coverage badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: images
          generate-branches-badge: false
          generate-summary: false

      # The saved badge does not appear when you pull code locally
      - name: Add coverage to CI repo
        # Limit frontpage badge to mainline code, not branches or PRs
        if: ${{ github.ref == 'refs/head/master' }}
        run: |
          cd images
          if [[ ! -z "$(git status --porcelain *.svg)" ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add *.svg
            git commit -m 'Autogenerated coverage badge'
            git push
          fi
